server:
  port: ${PORT}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: identity-service-route
          uri: lb://identity-service
          predicates:
            - Path=/api/users/**, /api/auth/**, /api/membership-ranks/**, /api/system-admin/**, /v3/api-docs/identity

        - id: shop-service-route
          uri: lb://shop-service
          predicates:
            - Path=/api/shops/**, /api/internal/shops/**, /v3/api-docs/shop

        - id: employee-service-route
          uri: lb://employee-service
          predicates:
            - Path=/api/employees/**, /api/shift-templates/**, /api/employee/unavailability/**, /api/schedules/**, /v3/api-docs/employee

        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/**, /v3/api-docs/inventory

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_SERVER_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: 1. Identity Service
        url: /v3/api-docs/identity
      - name: 2. Shop Service
        url: /v3/api-docs/shop
      - name: 3. Employee Service
        url: /v3/api-docs/employee
      - name: 4. Inventory Service
        url: /v3/api-docs/inventory
